name: wordix
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  cloud_firestore: ^5.4.1
  firebase_storage: ^12.3.0
  speech_to_text: ^7.0.0
  string_similarity: ^2.1.1
  http: ^1.2.2
  google_api_availability: ^5.0.0
  video_player: ^2.9.1
  fluttertoast: ^8.2.8
  provider: ^6.0.0
  shared_preferences: ^2.3.2
  fl_chart: ^0.69.0
  path_provider: ^2.1.4
  flutter_sound: ^9.16.0
  permission_handler: ^11.3.1
  hive: ^2.2.3
  record: ^5.1.2
  hive_flutter: ^1.1.0
  audioplayers: ^6.1.0
  googleapis: ^13.2.0
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  animated_text_kit: ^4.2.2
  shelf_router: ^1.1.4
  shelf: ^1.4.1
  convert: ^3.1.1
  dash_chat_2: ^0.0.21
  google_fonts: ^6.2.1
  dart_openai: ^5.1.0
  flutter_dotenv: ^5.1.0
  animated_splash_screen: ^1.3.0
  firebase_database: ^11.1.3
  google_generative_ai: ^0.4.6
  font_awesome_flutter: ^10.7.0
  lottie: ^3.1.2
  translator: ^1.0.0
  flutter_quill: ^10.7.5
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true

  
  assets:
      - assets/lesson_image.png
      - assets/lesson1.png
      - assets/lesson2.png
      - assets/audio_icon.png
      - assets/images_icon.png
      - assets/video_icon.png
      - assets/pdf_icon.png
      - assets/usa_flag.png
      - assets/horse.png
      - assets/dog.png
      - assets/cat.png
      - assets/tiger.png
      - assets/sad.png
      - assets/good.png
      - assets/ai_hand_waving.json
      - assets/ai_play.json
      - assets/Animation - 1715413486579.json
      - assets/chat_robot.json
      - assets/stars.png

  fonts:
    - family: Righteous Regular
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf


      

 